artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/uc?id=12evSAmXUhCo1XmJk7LOEahnxPqFgCNOT
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data
  tokenizer_name: aruca/pegasus_x-meeting-summarizer

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/dataset
  model_ckpt: aruca/pegasus_x-meeting-summarizer-gpt3.5

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/dataset
  model_path: artifacts/model_trainer/pegasus_x-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv